model: mlx-community/Meta-Llama-3.1-8B-Instruct-4bit
train: true
fine_tune_type: lora
data: "/Users/noktafa/Desktop/lora_train_etme/train_news.jsonl"
val_data: "/Users/noktafa/Desktop/lora_train_etme/valid_news.jsonl"
seed: 42
iters: 2700
batch_size: 4
learning_rate: 0.0001
num_layers: 16
adapter_path: "/Users/noktafa/Desktop/lora_train_etme/llama31_8b_haber_modeli_mlx/final_adapter"
steps_per_eval: 50
val_batches: 10
lora_parameters:
  rank: 16
  scale: 2.0
  dropout: 0.05
  keys:
    - self_attn.q_proj
    - self_attn.k_proj
    - self_attn.v_proj
    - self_attn.o_proj
    - mlp.gate_proj
    - mlp.up_proj
    - mlp.down_proj
